# Setup
title:            Halo
tagline:          'Halo tools'
description:      'Halo description.'

author:
  name:           'Hugo Dias'
  url:            https://twitter.com/hugomrdias

version:          0.0.1

# Config

url:              http://hugomrdias.github.io/halo

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl:          ''

# Pagination
paginate:         5

# Permalinks
permalink:        /:title/

# Dependencies
markdown:         redcarpet
highlighter:      pygments


gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - node_modules
  - gulpfile.js
  - package.json
  - less
  #- js
